/**
 * assets/assets is generated by the assets builder.
 */
import { covers } from 'assets/assets';
import Image from 'next/image';
import Link from 'next/link';

import { BlogPostMetadataPlus } from '@/lib/get_posts';

import { ENSAvatar } from './ENSAvatar';

type Properties = {
    post: BlogPostMetadataPlus;
};

export const BlogPostPreview = async ({ post }: Properties) => {
    const cover = Object.keys(covers).includes(post.file)
        ? await covers[post.file as keyof typeof covers]['cover-thumb']
              .then((image) => image.default)
              .catch(() => {
                  console.error('Failed to load cover for post', post.file);
              })
        : undefined;

    return (
        <Link
            href={'/post/' + post.slug}
            className="outline-ens-blue flex h-full w-full flex-col overflow-hidden rounded-lg border bg-white outline-2 transition-all hover:bg-gray-50 hover:outline"
        >
            <span className="bg-ens-grey1 aspect-cover w-full">
                {cover ? (
                    <Image
                        src={cover}
                        className="aspect-cover h-full w-full object-cover"
                        alt={post.title}
                    />
                ) : (
                    <img
                        src={post.cover}
                        className="aspect-cover h-full w-full object-cover"
                        alt={post.title}
                    />
                )}
            </span>
            <span className="flex flex-col gap-2 border-t p-5">
                <span className="flex w-full justify-between">
                    <span className="text-ens-blue block truncate text-lg font-bold">
                        {post.title}
                    </span>
                    <span>{/* TODO: Badges here */}</span>
                </span>
                <span className="pb-2 text-base">{post.description}</span>
                {/* <span className="flex grow flex-col p-2">
                    <span className="text-ens-grey2 text-xs">{post.date}</span>
                </span> */}
                {/* {post.tags && (
                    <span className="flex flex-wrap gap-1 px-2 pb-2">
                        {post.tags.map((tag) => (
                            <SmallTag tag={tag} />
                        ))}
                    </span>
                )} */}
                <span className="flex w-full items-end justify-between">
                    <span className="flex items-center gap-2">
                        <span className="flex -space-x-2">
                            {post.authors.map((author) => (
                                <ENSAvatar name={author} size="small" />
                            ))}
                        </span>
                        <span>{post.authors.join(', ')}</span>
                    </span>
                    <span className="text-gray-400">2 min read</span>
                </span>
            </span>
        </Link>
    );
};
